### PR TITLE
Rename Web Foundations Slack channel

### PR DESCRIPTION
**Pull request by atesgoral**
## Description

Rename Slack channel and update documentation links

Part of https://github.com/Shopify/web-foundations/issues/118

## Type of change

Documentation fix

- [ ]  Patch: Bug/ Documentation fix (non-breaking change which fixes an issue or adds documentation)
- [ ]  Minor: New feature (non-breaking change which adds functionality)
- [ ]  Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] ~~I have added a changelog entry, prefixed by the type of change noted above~~

### CODE REVIEW

**Comment by kddeisz** [comment]
Sorry but I have no idea what the repo is, so not really sure I can review this.

**Comment by atesgoral** [comment]
@kddeisz Just need to confirm the content is correct (i.e. the links are no longer broken etc.) I'm willing to YOLO merge this if you're OK. I was just trying to get a +1 from one of the owners of this repo and you seemed to have recently contributed to it.

**Comment by kddeisz** [comment]
@atesgoral yeah I only contributed to modify the `service.yml` for ServicesDB. Unfortunately don't know anything about this repo in particular. The owner is listed in ServicesDB (https://services.shopify.io/services/libra-web-tools) as Shopify Pay Installments which is linked to the @Shopify/money-infrastructure-ops team, they would be the best choice for review.

**Comment by atesgoral** [comment]
Thanks @kddeisz! I should have checked that myself 😅

**Pull request closed without merging**
